#ifndef HW_REGS_H
#define HW_REGS_H 1

#include "xgpio_l.h"

/* Servo and Motor Control Registers */
#define FIN_0_PWM_ADDR      XPAR_IP_PWM_2020P2_0_S00_AXI_BASEADDR
#define FIN_1_PWM_ADDR      XPAR_IP_PWM_2020P2_1_S00_AXI_BASEADDR
#define FIN_2_PWM_ADDR      XPAR_IP_PWM_2020P2_2_S00_AXI_BASEADDR
#define FIN_3_PWM_ADDR      XPAR_IP_PWM_2020P2_3_S00_AXI_BASEADDR

#define MTR_0_PWM_ADDR      XPAR_IP_PWM_2020P2_4_S00_AXI_BASEADDR

/* Receiver Registers */
#define PITCH_Y_PWMR_ADDR   XPAR_IP_PWMR_0_S00_AXI_BASEADDR
#define ROLL_X_PWMR_ADDR    XPAR_IP_PWMR_1_S00_AXI_BASEADDR
#define YAW_Z_PWMR_ADDR     XPAR_IP_PWMR_2_S00_AXI_BASEADDR
#define THROTTLE_PWMR_ADDR  XPAR_IP_PWMR_3_S00_AXI_BASEADDR

/* IMU Registers */
#define IMU_SER_ADDR        XPAR_IP_IMU_2020P2_0_S00_AXI_BASEADDR

/* GPIO PWM Sync */
#define PWM_SYNC_DEVICE_ID  XPAR_AXI_GPIO_0_DEVICE_ID
#define PWM_SYNC_ADDR       XPAR_GPIO_0_BASEADDR
#define PWM_CHANNEL         XGPIO_IR_CH1_MASK

/* Test UART */
#define TEST_UART_DEVICE_ID XPAR_AXI_UARTLITE_0_DEVICE_ID
#define TEST_UART_ADDR      XPAR_AXI_UARTLITE_0_BASEADDR
#endif /* HW_REGS_H */
