# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc/Zybo-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hb_0_0/design_1_hb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hb_0_0 || ORIG_REF_NAME==design_1_hb_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ip_pwmr_0_0/design_1_ip_pwmr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ip_pwmr_0_0 || ORIG_REF_NAME==design_1_ip_pwmr_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ip_pwmr_0_1/design_1_ip_pwmr_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ip_pwmr_0_1 || ORIG_REF_NAME==design_1_ip_pwmr_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ip_pwmr_0_2/design_1_ip_pwmr_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ip_pwmr_0_2 || ORIG_REF_NAME==design_1_ip_pwmr_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ip_pwmr_2_0/design_1_ip_pwmr_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ip_pwmr_2_0 || ORIG_REF_NAME==design_1_ip_pwmr_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_gpio_breakkout_0_1/design_1_gpio_breakkout_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_gpio_breakkout_0_1 || ORIG_REF_NAME==design_1_gpio_breakkout_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ip_pwm_2020p2_0_0/design_1_ip_pwm_2020p2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ip_pwm_2020p2_0_0 || ORIG_REF_NAME==design_1_ip_pwm_2020p2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ip_pwm_2020p2_0_1/design_1_ip_pwm_2020p2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ip_pwm_2020p2_0_1 || ORIG_REF_NAME==design_1_ip_pwm_2020p2_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ip_pwm_2020p2_0_2/design_1_ip_pwm_2020p2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ip_pwm_2020p2_0_2 || ORIG_REF_NAME==design_1_ip_pwm_2020p2_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ip_pwm_2020p2_0_3/design_1_ip_pwm_2020p2_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ip_pwm_2020p2_0_3 || ORIG_REF_NAME==design_1_ip_pwm_2020p2_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ip_pwm_2020p2_0_4/design_1_ip_pwm_2020p2_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ip_pwm_2020p2_0_4 || ORIG_REF_NAME==design_1_ip_pwm_2020p2_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ip_imu_2020p2_0_1/design_1_ip_imu_2020p2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ip_imu_2020p2_0_1 || ORIG_REF_NAME==design_1_ip_imu_2020p2_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/14086/Documents/topper/projs/git/github/rdl1/rdl1.gen/sources_1/bd/design_1/design_1_ooc.xdc
